// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLflqYi_x5VV_r4keb3QPUvzDOZXmFmTo',
    appId: '1:626226983746:web:7dfbfd1381d96a998a8edb',
    messagingSenderId: '626226983746',
    projectId: 'try-flutter-map',
    authDomain: 'try-flutter-map.firebaseapp.com',
    storageBucket: 'try-flutter-map.appspot.com',
    measurementId: 'G-JYM4YP7M49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-ALNZoPlYfqYLqublzhaaRQoRYf5NS0',
    appId: '1:626226983746:android:e27092a8262175658a8edb',
    messagingSenderId: '626226983746',
    projectId: 'try-flutter-map',
    storageBucket: 'try-flutter-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1kb5j5D5Fvt8OFSMG22T_SuPIfHHBNp0',
    appId: '1:626226983746:ios:7a1d7b3269bfe6b78a8edb',
    messagingSenderId: '626226983746',
    projectId: 'try-flutter-map',
    storageBucket: 'try-flutter-map.appspot.com',
    iosClientId: '626226983746-tl44qvo29ni4o5sk5rbmkl7lb25bk9po.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFlutterMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1kb5j5D5Fvt8OFSMG22T_SuPIfHHBNp0',
    appId: '1:626226983746:ios:7a1d7b3269bfe6b78a8edb',
    messagingSenderId: '626226983746',
    projectId: 'try-flutter-map',
    storageBucket: 'try-flutter-map.appspot.com',
    iosClientId: '626226983746-tl44qvo29ni4o5sk5rbmkl7lb25bk9po.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryFlutterMap',
  );
}
